### ISSUE TITLE
Missing dependencies when building the cxf-rest quickstart

### ISSUE THREAD

**Issue by jpsmoura** [jboss-fuse/quickstarts#15]
jserrade-OSX:rest jmoura$ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.fuse.bom:jboss-fuse-parent:pom:6.3.0.redhat-SNAPSHOT @ line 99, column 19
[ERROR] 'dependencies.dependency.version' for org.apache.servicemix.specs:org.apache.servicemix.specs.jsr339-api-2.0:jar is missing. @ line 120, column 17
[ERROR] 'dependencies.dependency.version' for org.slf4j:slf4j-api:jar is missing. @ line 129, column 17
[ERROR] 'dependencies.dependency.version' for junit:junit:jar is missing. @ line 136, column 17
[ERROR] 'dependencies.dependency.version' for commons-httpclient:commons-httpclient:jar is missing. @ line 146, column 17
[ERROR] 'dependencies.dependency.version' for commons-logging:commons-logging:jar is missing. @ line 152, column 17
[ERROR] 'dependencies.dependency.version' for org.slf4j:slf4j-log4j12:jar is missing. @ line 161, column 17
[ERROR] 'dependencies.dependency.version' for org.apache.cxf:cxf-rt-frontend-jaxrs:jar is missing. @ line 172, column 17

**Comment by cunningt** [comment]
This is most likely from building without the parent pom built first.
