### ISSUE TITLE
bundle deployed in jboss fuse not getting stopped

### ISSUE THREAD

**Issue by partha006** [jboss-fuse/quickstarts#25]
I am beginner to jboss fuse i have tried to deploy the bundle in the in the jboss fuse server but its status is **creating**
 
 
[ 349] [Active     ] [Creating    ] [       ] [   80] Empty Camel Blueprint Example [splitter-aggregator] (1.0.2.SNAPSHOT)
 
So i was trying to stop or uninstall the bundle by using below commands
 
osgi:stop 349
or
osgi:uninstall --force 349
or
osgi:uninstall 349
 
but its not getting stop or uninstalled , i am getting the following error while running the above command
 
 
Error executing command: Error stopping bundles:
        **Unable to stop bundle 349: Bundle splitter-aggregator [349] cannot be stopped since it is already stopping.**
 
Kindly help me to resolve the issue.

**Comment by cunningt** [comment]
This has nothing to do with the SwitchYard quickstarts module.     Closing.
