### ISSUE TITLE
fuse ear-deployment : Update the README.md file for Testing

### ISSUE THREAD

**Issue by kirenpillay** [jboss-fuse/quickstarts#26]
In the switchyard-ear-deployment quickstart, the README.md should say "switch to order-consumer folder" as show below. Currently it does nothing.

4. Switch to order-consumer folder

        cd ${project.parent.folder}/order-consumer  

5. Test the application

        mvn exec:java

6. Undeploy the EAR

        mvn clean -Pdeploy

**Comment by cunningt** [comment]
Logged as ENTESB-6619.
